name: isort

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
      - name: Run isort
        run: |
          isort --check --diff .